[DEFAULTS]
# Define default threshold values for the different the different stages during
# cooldown and warmup procedures
still_full_cd = 5
still_4K_cd = 7
still_coldinsert = 6
baseT = 0.01
circ_warning = 0.1
warmup = 290

# Define channel numbers of the temperature sensors
channel_nr_still = 5
channel_nr_mxc = 6


[MQTT]
# Define hostname (IP address of BFTC API), port and topic to subscribe to
hostname = 192.168.10.54
port = 1883
topic = channel/measurement/listen


[DISCORD]
# Define target channel and enter access token of the user
channel_url = <discord channel url>
access_token = <discord access token>
